version: '3.5'

services:
  # redis:
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./container_data/redis:/root/redis

# Use root/example as user/password credentials
  postgres:
      image: postgres
      environment:
        POSTGRES_USER: ${POSTGRES_USER:-postgres}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
        PGDATA: /data/postgres
      volumes:
        - ./.container_data/postgres:/data/postgres
      ports:
        - "5432:5432"
      restart: unless-stopped


networks:
  default:
    driver: bridge